pipeline {
  agent any
  stages {
    stage('Run functional test cases') {
      steps {
      bat "cd CDSIT-MobAutomation-Project"
       bat "mvn clean install -DjenkinsBrowser=${params.browser} -Dcucumber.options=\"--tags ${params.tagName}\""
      }
    }
  }
}